### ISSUE TITLE
[ISSUE] 이메일 인증 절차를 위한 Redis 연동

### ISSUE THREAD

**Issue by isayaksh** [korean-learn/k-learn-api#1]
# ✏️ Description
현재 개발이 필요한 내역은 다음과 같다.
1. 이메일을 이용한 회원가입 절차 시 이메일 인증
2. 비밀번호 갱신을 위한 이메일 인증

인증번호 관리르 위한 인모메리 DB의 필요성이 발생하여 Redis 연동 작업을 진행한다. 

# 🛠 Features
- Redis 로컬에서 테스트 후, 클라우드에 배포

# ❗️Warnning
- [ ] Redis 관련 ID, PASSWORD가 노출되지 않도록 작업진행
- [ ] 환경변수(.env) 클라우드 환경에서도 갱신해줄 것

**Comment by isayaksh** [comment]
# 라이브러리 추가
`build.gradle` 파일에 redis 라이브러리르 추가해준다.
```
implementation 'org.springframework.boot:spring-boot-starter-data-redis'
```

# 환경변수 등록
`application.yml` 파일에 환경변수 값을 등록한다.
```
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
```
